# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clk_div.xdc

# Block Designs: bd/clk_div/clk_div.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div || ORIG_REF_NAME==clk_div} -quiet] -quiet

# IP: bd/clk_div/ip/clk_div_processing_system7_0_0/clk_div_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div_processing_system7_0_0 || ORIG_REF_NAME==clk_div_processing_system7_0_0} -quiet] -quiet

# IP: bd/clk_div/ip/clk_div_axi_gpio_0_0/clk_div_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div_axi_gpio_0_0 || ORIG_REF_NAME==clk_div_axi_gpio_0_0} -quiet] -quiet

# IP: bd/clk_div/ip/clk_div_ps7_0_axi_periph_0/clk_div_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div_ps7_0_axi_periph_0 || ORIG_REF_NAME==clk_div_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/clk_div/ip/clk_div_rst_ps7_0_1M_0/clk_div_rst_ps7_0_1M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div_rst_ps7_0_1M_0 || ORIG_REF_NAME==clk_div_rst_ps7_0_1M_0} -quiet] -quiet

# IP: bd/clk_div/ip/clk_div_clk_div_top_0_0/clk_div_clk_div_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div_clk_div_top_0_0 || ORIG_REF_NAME==clk_div_clk_div_top_0_0} -quiet] -quiet

# IP: bd/clk_div/ip/clk_div_auto_pc_0/clk_div_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_div_auto_pc_0 || ORIG_REF_NAME==clk_div_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_processing_system7_0_0/clk_div_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_div_processing_system7_0_0 || ORIG_REF_NAME==clk_div_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_axi_gpio_0_0/clk_div_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_div_axi_gpio_0_0 || ORIG_REF_NAME==clk_div_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_axi_gpio_0_0/clk_div_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_axi_gpio_0_0/clk_div_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_div_axi_gpio_0_0 || ORIG_REF_NAME==clk_div_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_rst_ps7_0_1M_0/clk_div_rst_ps7_0_1M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_div_rst_ps7_0_1M_0 || ORIG_REF_NAME==clk_div_rst_ps7_0_1M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_rst_ps7_0_1M_0/clk_div_rst_ps7_0_1M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_div_rst_ps7_0_1M_0 || ORIG_REF_NAME==clk_div_rst_ps7_0_1M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/ip/clk_div_auto_pc_0/clk_div_auto_pc_0_ooc.xdc

# XDC: c:/Users/17877/Vivado_Projects/project_clk_div_scale_auto/project_clk_div_scale_auto.gen/sources_1/bd/clk_div/clk_div_ooc.xdc
